### ISSUE TITLE
Variables names and methods names should be lowercase

### ISSUE THREAD

**Issue by avermeulen** [Unalo/BikeRide#1]
https://github.com/Unalo/BikeRide/blob/b80381bb33b686a191586af54864ca2c90f65a4c/tests/bicycles/FunRideTests.java#L14-L16

It should be:

```java
       Bicycle tandem = new Tandem ();
        Bicycle mountainBike = new MountainBike ();
        Bicycle toadBike = new RoadBike ();
```

This should be:

```java
        funRide.accept (Tandem); 
        funRide.accept (RoadBike);
```

@Unalo

**Comment by Unalo** [comment]
Fixed that, all variable names and methods in lowercase now.
Thanks.
@avermeulen
